import React, { Dispatch, SetStateAction } from 'react';

export const MainContext = React.createContext<{
  userInput: string,
  wordIndex: number,
  isTimeOut: boolean,
  setIsTimeOut: React.Dispatch<React.SetStateAction<boolean>>,
  startTimer: boolean,
  setStartTimer: React.Dispatch<React.SetStateAction<boolean>>,
  countDown: number,
  wordsStack: Array<string>,
  setWordsStack: Dispatch<SetStateAction<string[]>>,
  computedWords: Array<string>,
  setComputedWords: React.Dispatch<React.SetStateAction<Array<string>>>,
  correctWords: Array<string>,
  setCorrectWords: React.Dispatch<React.SetStateAction<Array<string>>>,
  setCountDown: React.Dispatch<React.SetStateAction<number>>,
  setWordIndex: React.Dispatch<React.SetStateAction<number>>,
  setUserInput: React.Dispatch<React.SetStateAction<string>>,
  score: number | undefined,
  setScore: React.Dispatch<React.SetStateAction<number>>,
  offSet: number | undefined,
  setOffSet: React.Dispatch<React.SetStateAction<number | undefined>>,
  yFocusedPosition: number | undefined,
  setYFocusedPosition: React.Dispatch<React.SetStateAction<number | undefined>>,
  yNextPosition: number | undefined,
  setYNextPosition: React.Dispatch<React.SetStateAction<number | undefined>>,
  horizontalPosition: number | undefined,
  setHorizontalPosition: React.Dispatch<React.SetStateAction<any>>,
  letterWidth: number | undefined,
  setLetterWidth: React.Dispatch<React.SetStateAction<any>>,
  fontSize: number,
  language: string,
  setFontSize: React.Dispatch<React.SetStateAction<number>>,
  setLanguage: React.Dispatch<React.SetStateAction<string>>,
  onRestart: any,
    }>({} as any);
