name: PR-Checks

on: 
  pull_request:
    branches: [main]

jobs:
  pr-checks:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: 'Build docker image'
        run: yarn docker:build-staging

      - name: 'Run docker container'
        run: yarn docker:start-staging
