name: PR-Checks

on: 
  pull_request:
    branches: [main]

jobs:
  # pr-checks:
  #   runs-on: ubuntu-latest
  #   timeout-minutes: 30

  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v2

  #     - name: Setup Node.js
  #       uses: actions/setup-node@v2
  #       with:
  #         node-version: '14'

  #     - name: 'Install dependecies'
  #       run: yarn

  #     - name: 'Lint code base'
  #       run: yarn lint

  #     - name: 'Run tests over monorepo'
  #       run: yarn test

  #     - name: 'Build packages'
  #       run: yarn build

  #     - name: 'Build docker image'
  #       run: yarn docker:build-staging

  deploy:
    runs-on: ubuntu-latest
    # needs: pr-checks

    steps:
      - name: Deploy to VPS (prod) via SSH action
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: 22
          script: |
            mkdir DEPLOY_TEST
