name: PR-checks

on: 
  pull_request

jobs:
  pr-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Go to client and run lint
        run: cd packages/client && yarn && yarn lint
      - name: Go to server and run tests
        run: cd ../server && yarn && yarn test
      - name: Run linter on server
        run: yarn lint
      - name: Go to utils and run tests
        run: cd ../utils && yarn && yarn test
      - name: Run linter on utils
        run: yarn lint
      - name: 'monorepo: lerna run build'
        run: CI=false lerna run build # in order to ignore warns when building
        