name: PR-Checks

on: 
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: 'Turbo run yarn'
        run: turbo run yarn

      - name: 'Turbo run lint'
        run: turbo run lint

      - name: 'Turbo run test'
        run: turbo run test

      - name: 'Turbo run build'
        run: turbo run build