name: Deploy in production

on: 
  push:
    branches: [main]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: 'Build docker image and runs it'
        run: yarn build:docker-prod

      - name: 'Build docker image and runs it'
        run: yarn start:docker-prod

    deploy:
      runs-on: ubuntu-latest
      needs: build_and_push_in_production

      steps:
        - name: Deploy to VPS (prod) via SSH action
          uses: appleboy/ssh-action@v0.1.3
          with:
            host: ${{ secrets.VPS_HOST }}
            username: ${{ secrets.VPS_USERNAME }}
            password: ${{ secrets.VPS_PASSWORD }}
            port: 22
             script: |
               mkdir DEPLOY_TEST
            # script: |
            #   cd SQRIB
            #   docker-compose stop
            #   docker-compose rm -f
            #   docker-compose pull
            #   docker-compose up -d